on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  owasp:
    name: OWASP Check
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://www.gerdemann.me/'
